//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Permit
    {
        public int Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Storage_Id { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Production_Date { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
